#!/usr/bin/env python3
"""Refresh _data/scholar.yml with citation counts from Google Scholar.

Reads the profile's `gscholar` id from _data/profile.yml, fetches the
author's citation totals and per-publication citation counts via the
`scholarly` package, and writes the result to _data/scholar.yml for
Jekyll to render. Run on a schedule by .github/workflows/update-scholar.yml.

Exits non-zero (without touching the data file) if the fetch fails, so a
transient Scholar block or scraper breakage never wipes out good data.
"""
import datetime
import re
import sys
from pathlib import Path

import yaml
from scholarly import scholarly

ROOT = Path(__file__).resolve().parent.parent
PROFILE_PATH = ROOT / "_data" / "profile.yml"
OUTPUT_PATH = ROOT / "_data" / "scholar.yml"


def load_gscholar_id() -> str:
    profile = yaml.safe_load(PROFILE_PATH.read_text(encoding="utf-8"))
    gscholar = profile.get("gscholar")
    if not gscholar:
        raise SystemExit("No gscholar id set in _data/profile.yml")
    # Support either a bare author id or a full profile URL.
    match = re.search(r"user=([\w-]+)", gscholar)
    return match.group(1) if match else gscholar


def fetch_author_data(author_id: str) -> dict:
    author = scholarly.search_author_id(author_id)
    author = scholarly.fill(author, sections=["basics", "indices", "counts", "publications"])

    by_title = {}
    for pub in author.get("publications", []):
        title = (pub.get("bib") or {}).get("title")
        cites = pub.get("num_citations")
        if title and cites is not None:
            by_title[title.strip().lower()] = int(cites)

    return {
        "updated": datetime.date.today().isoformat(),
        "citations": author.get("citedby", 0),
        "hindex": author.get("hindex", 0),
        "i10index": author.get("i10index", 0),
        "by_title": by_title,
    }


def main() -> int:
    author_id = load_gscholar_id()
    try:
        data = fetch_author_data(author_id)
    except Exception as exc:  # noqa: BLE001 - any scrape failure should be non-fatal to the site
        print(f"Failed to fetch Google Scholar data: {exc}", file=sys.stderr)
        return 1

    if not data["by_title"]:
        print("Fetched zero publications; refusing to overwrite existing data.", file=sys.stderr)
        return 1

    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/update_scholar.py — do not edit by hand.\n")
        yaml.safe_dump(data, f, allow_unicode=True, sort_keys=False, width=1000)

    print(f"Updated {OUTPUT_PATH} ({data['citations']} citations, {len(data['by_title'])} publications).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
